import fs from "node:fs";
import path from "node:path";
import { minimatch } from "minimatch";
import {
  normalizePolicyPath,
  parsePolicyFile,
  type ParsedPolicyRule,
} from "../policy/parser.js";

export type ScanSeverity = "critical" | "high" | "medium";

export interface ScanResult {
  filePath: string;
  severity: ScanSeverity;
  reason: string;
  alreadyCoveredByPolicy: boolean;
}

interface SensitiveFileRule {
  severity: ScanSeverity;
  reason: string;
  matches(filePath: string): boolean;
}

export interface ScanWorkspaceOptions {
  rootDir?: string;
  policyPath?: string;
}

const ignoredDirectories = new Set([".git", "node_modules", "dist"]);

const sensitiveFileRules: SensitiveFileRule[] = [
  {
    severity: "critical",
    reason: "Environment variable file",
    matches: (filePath) => {
      const baseName = path.posix.basename(filePath);
      return baseName === ".env" || baseName.startsWith(".env.");
    },
  },
  {
    severity: "critical",
    reason: "Private key or certificate material",
    matches: (filePath) =>
      minimatch(filePath, "**/*.{pem,key,pfx,p12}", { dot: true, nocase: true }),
  },
  {
    severity: "critical",
    reason: "SSH private key",
    matches: (filePath) => {
      const baseName = path.posix.basename(filePath);
      return baseName === "id_rsa" || baseName === "id_ed25519";
    },
  },
  {
    severity: "high",
    reason: "Credential JSON file",
    matches: (filePath) => {
      const baseName = path.posix.basename(filePath);
      return (
        baseName === "credentials.json" ||
        minimatch(baseName, "service-account*.json", { nocase: true })
      );
    },
  },
  {
    severity: "high",
    reason: "Cloud or SSH credential configuration",
    matches: (filePath) =>
      filePath === ".aws/credentials" || filePath === ".ssh/config",
  },
  {
    severity: "medium",
    reason: "Database export or configuration",
    matches: (filePath) => {
      const baseName = path.posix.basename(filePath);
      return (
        minimatch(baseName, "*.{sql,dump}", { nocase: true }) ||
        baseName === "database.json"
      );
    },
  },
];

export const defaultPolicyRules = [
  ".env",
  ".env.*",
  "*.pem",
  "*.key",
  "id_rsa",
  "id_ed25519",
  "*.pfx",
  "*.p12",
  "credentials.json",
  "service-account*.json",
  ".aws/credentials",
  ".ssh/config",
  "*.sql",
  "*.dump",
  "database.json",
];

export function getDefaultPolicyContent(): string {
  return [
    "# AIGuard default sensitive-file policy",
    "# Generated by `aiguard init`.",
    ...defaultPolicyRules,
    "",
  ].join("\n");
}

export function scanWorkspace(options: ScanWorkspaceOptions = {}): ScanResult[] {
  const rootDir = path.resolve(options.rootDir ?? process.cwd());
  const policyPath = path.resolve(rootDir, options.policyPath ?? ".aipolicy");
  const policyRules = loadPolicyRules(policyPath);
  const results: ScanResult[] = [];

  for (const filePath of walkFiles(rootDir)) {
    const relativePath = normalizePolicyPath(path.relative(rootDir, filePath));
    const matchingSensitiveRule = sensitiveFileRules.find((rule) =>
      rule.matches(relativePath),
    );

    if (!matchingSensitiveRule) continue;

    results.push({
      filePath: relativePath,
      severity: matchingSensitiveRule.severity,
      reason: matchingSensitiveRule.reason,
      alreadyCoveredByPolicy: isCoveredByPolicy(relativePath, policyRules),
    });
  }

  return results.sort((a, b) => a.filePath.localeCompare(b.filePath));
}

export function isCoveredByPolicy(
  filePath: string,
  policyRules: ParsedPolicyRule[],
): boolean {
  const matchingRule = findLastMatchingPolicyRule(
    normalizePolicyPath(filePath),
    policyRules,
  );
  return matchingRule !== undefined && !matchingRule.negated;
}

function loadPolicyRules(policyPath: string): ParsedPolicyRule[] {
  try {
    return parsePolicyFile(fs.readFileSync(policyPath, "utf-8"));
  } catch {
    return [];
  }
}

function* walkFiles(rootDir: string): Generator<string> {
  for (const entry of fs.readdirSync(rootDir, { withFileTypes: true })) {
    if (entry.isDirectory() && ignoredDirectories.has(entry.name)) continue;

    const entryPath = path.join(rootDir, entry.name);
    if (entry.isDirectory()) {
      yield* walkFiles(entryPath);
      continue;
    }

    if (entry.isFile()) {
      yield entryPath;
    }
  }
}

function findLastMatchingPolicyRule(
  filePath: string,
  policyRules: ParsedPolicyRule[],
): ParsedPolicyRule | undefined {
  let matchingRule: ParsedPolicyRule | undefined;

  for (const rule of policyRules) {
    if (matchesPolicyRule(filePath, rule)) {
      matchingRule = rule;
    }
  }

  return matchingRule;
}

function matchesPolicyRule(filePath: string, rule: ParsedPolicyRule): boolean {
  const options = { dot: true, nocase: true };
  if (rule.pattern.includes("/")) {
    return minimatch(filePath, rule.pattern, options);
  }

  return minimatch(path.posix.basename(filePath), rule.pattern, options);
}
